---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: torbridgeconfigs.tor.fulvio.dev
spec:
  group: tor.fulvio.dev
  names:
    kind: TorBridgeConfig
    listKind: TorBridgeConfigList
    plural: torbridgeconfigs
    singular: torbridgeconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TorBridgeConfig is the Schema for the TorBridgeConfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TorBridgeConfigSpec defines the desired state of TorBridgeConfig
            properties:
              contactInfo:
                type: string
              dirPort:
                type: integer
              extOrPort:
                type: string
              image:
                type: string
              nickname:
                type: string
              orPort:
                type: integer
              originPort:
                type: integer
              redirectPort:
                type: integer
              relayType:
                type: string
              serverTransportListenAddr:
                type: string
              serverTransportPlugin:
                type: string
            type: object
          status:
            description: TorBridgeConfigStatus defines the observed state of TorBridgeConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
